site_name: Docs Website
site_description: Personal document collection hosted on GitHub Pages
nav:
    - Home: index.md
    - Files:
          - Dockers: Dockers/index.md
          - git: git/index.md
          - linux-setup: linux-setup/index.md
          - python: python/index.md
          - ssh: ssh/index.md
          - vscode: vscode/index.md
theme:
    name: material
docs_dir: site_docs
