site_name: Vinald's Docs
site_description: Personal documentation collection 

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo

nav:
  - Home: index.md
  - Git:
      - Commands: git/commands.md
      - gitIgnore: git/gitIgnore.md
      - SSH Key Setup: git/ssh_key_setup.md
  - Python:
      - Creating Virtual Environment: Python/creating_virtual_environment.md
      - Packages: Python/packages.md
  - Docker:
      - Index: Docker/index.md
      - Images: Docker/images.md
  - Database:
      - Index: Database/index.md
      - Setup Postgres: Database/setup_postgres_db_in_docker.md
  - Linux:
      - Index: Linux/index.md
      - Packages: Linux/packages.md
  - VSCode:
      - Index: VSCode/index.md
      - Extensions: VSCode/extensions.md
  - SSH:
      - Index: ssh/index.md
      - Doc: ssh/doc.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - abbr
